# Generated by Django 3.2 on 2021-04-07 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_file'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file',
            table='task_files',
        ),
    ]
