# Generated by Django 3.2 on 2021-04-07 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_file_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file',
            table='documents',
        ),
    ]
