# Generated by Django 3.2 on 2021-04-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_file_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='TaskFile',
        ),
    ]
