# Generated by Django 3.2 on 2021-04-07 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_rename_file_taskfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskFile',
            new_name='TaskDocuments',
        ),
    ]
