# Generated by Django 3.2 on 2021-04-07 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_rename_taskfile_taskdocuments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskDocuments',
            new_name='TaskFile',
        ),
    ]
